name: pipelineiq
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip

  # Core data stack
  - pandas=2.2
  - numpy=1.26
  - scikit-learn=1.4
  - scipy

  # Gradient boosting
  - xgboost
  - lightgbm

  # Hyperparameter optimization
  - optuna

  # Experiment tracking
  - mlflow

  # Explainability
  - shap

  # Visualization
  - matplotlib
  - seaborn
  - plotly

  # Dashboard
  - streamlit

  # Utilities
  - pip:
    - ydata-profiling       # data quality reports
    - sweetviz              # EDA comparison reports
    - category-encoders     # advanced categorical encoding